port: 7890
redir-port: 7891
socks-port: 7892
mixed-port: 7893
tproxy-port: 7894

allow-lan: true
bind-address: '*'
routing-mark: 0x100
mode: rule
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: ui
secret: anu
geodata-mode: true
geodata-loader: memconservative
global-client-fingerprint: chrome
keep-alive-interval: 15
tcp-concurrent: true
unified-delay: true
tun:
  enable: false
  stack: gvisor
  device: Meta
  dns-hijack:
    - any:53
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
  skip-domain:
    - '+.microsoft.com'
    - '+.windows.com'
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:1053
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  fallback:
    - 1.1.1.1
    - 1.0.0.1
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
profile:
  store-selected: true
  store-fake-ip: false
proxy-providers:
  proxy:
    type: file
    path: ./proxy_providers/proxy.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Umum
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - proxy
rules:
  - MATCH,Umum