services:
  fusiontunx-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIHOMO_VERSION: v1.19.17
    image: fusiontunx:dev
    container_name: fusiontunx-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9090:9090"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./files:/etc/fusiontunx
      - ./src/bin/fusiontunx-linux-amd64:/usr/share/fusiontunx/fusiontunx
      - ./src/configs/app.yaml:/etc/fusiontunx/app.yaml
      - dev-logs:/var/log
    environment:
      - TZ=Asia/Jakarta
      - LOG_LEVEL=debug
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  dev-logs:
